---
title: "Avian Predation Reporting"
author: "Sam Graf"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse) 
library(lubridate)
library(DT)
library(plotly)
library(shiny)

if(!exists("indiv_datasets_list")){
  indiv_datasets_list <- readRDS("../../../data/flatFilesforApp/indiv_datasets_list.rds")
}
if(!exists("avianPredationList")){
  avianPredationList <- readRDS("../../../data/flatFilesforApp/possibleAvianPredationDFs.rds")
}
if(!exists("combinedData_df_list")){
  combinedData_df_list <- readRDS("../../../data/flatFilesforApp/combinedData_df_list.rds")
}
if(!exists("movements_list")){
  movements_list <- readRDS("../../../data/flatFilesforApp/movements_list.rds")
}
neededFunctions <- c("getSequences.R")

for (i in neededFunctions) {
  source(paste0("../../../functions/",i))
}

movementColorsValues <- c("purple", "#eb0e2b", "#FF8C00", "gray", "#22bd74") #, "#66FF00"
movementColors <- setNames(movementColorsValues, sort(unique(movements_list$Movements_df$movement_only)))

#bring in data
```
### Downstream from Hitching Post to Red Barn: Non Avian Predated Fish
```{r wrangling, echo = FALSE, include=TRUE, warning=FALSE,message=FALSE,error=FALSE}
allEventsAvianExcluded <- combinedData_df_list$All_Events %>%
    dplyr::filter(!TAG %in% unique(indiv_datasets_list$avian_preddata$TagID), 
                  !Species %in% c("MERG")) 

HPRBSequences <- invisible(getSequences(allEventsAvianExcluded, c("HP"), "", c("RB"), c("M1", "M2")))
RBHPSequences <- invisible(getSequences(allEventsAvianExcluded, c("RB"), "", c("HP"), c("M1", "M2")))

easyViewingTime <- function(time) {
  diff_secs <- abs(as.numeric(time))
  
  if (diff_secs < 60) {
    return(paste(diff_secs, "seconds"))
  } else if (diff_secs < 3600) {
    return(paste(round(diff_secs / 60, 2), "minutes"))
  } else if (diff_secs < 86400) {
    return(paste(round(diff_secs / 3600, 2), "hours"))
  } else {
    return(paste(round(diff_secs / 86400, 2), "days"))
  }
}

easyViewingTime_vec <- Vectorize(easyViewingTime)
# usseqsNoMerg <- upstreamSeqs %>%
#   filter(!Species %in% c("MERG"))
# 
# dsseqsNoMerg <- downstreamSeqs %>%
#   filter(!Species %in% c("MERG"))

summarizedDs <- HPRBSequences %>%
  ungroup() %>%
  summarize(meanJourneyLength = easyViewingTime(mean(`Time Between First/Last Detections (For Sorting)`)), 
            medianJourneyLength = easyViewingTime(median(`Time Between First/Last Detections (For Sorting)`)), 
            sdDevJourneyLength = easyViewingTime(sd(`Time Between First/Last Detections (For Sorting)`)), 
            minJourneyLength = easyViewingTime(max(`Time Between First/Last Detections (For Sorting)`)), 
            maxJourneyLength = easyViewingTime(min(`Time Between First/Last Detections (For Sorting)`))) %>%
  mutate(SequenceDIrection = "downstreamHPtoRB") %>%
  pivot_longer(
    cols = -SequenceDIrection,
    names_to = c("downstreamHPtoRB"),
    #names_pattern = "(mean|min|max|median|sd)(.*)",
    values_to = "value"
  )

datatable(summarizedDs, 
          caption = paste0("Downstream HP to RB Sequences Summarized (", nrow(HPRBSequences), " journeys): Non-Avian Predated Fish"),
  options = list(
    pageLength = 10,
    autoWidth = TRUE
  ),
  filter = list(
  position = 'top', clear = FALSE
),
  rownames = FALSE
  )


plot <- HPRBSequences %>%
  #mutate()
  ggplot(aes(x = abs(as.numeric(`Time Between First/Last Detections (For Sorting)`)),
             text = paste0("Range: ", easyViewingTime_vec(round(after_stat(xmin), 2)), " to ", 
                           easyViewingTime_vec(round(after_stat(xmax), 1)), #" seconds",
                    "<br>Count: ", after_stat(count))
             #text = `Time Between First/Last Detections (User Friendly)`
             )
         ) +
  geom_histogram(bins = 50, color = "steelblue", fill = "steelblue") +
  scale_x_log10(labels = scales::label_log()) +
  labs(
    title = "Log Duration Distribution of Downstream Journeys From HP to RB: Non-Avian Predated Fish",
    x = "Log Time Difference (seconds)",
    y = "Frequency", 
    caption = "Avian Predated Tags Excluded"
  ) +
  theme_classic()
ggplotly(plot, tooltip = "text")
```

### Upstream from Red Barn To Hitching Post: Non-Avian Predated Fish
```{r upstream, echo = FALSE, include=TRUE, warning=FALSE,message=FALSE,error=FALSE}
####UPSTREAM SEQUENCES
summarizedUS <- RBHPSequences %>%
  ungroup() %>%
  summarize(meanJourneyLength = easyViewingTime(mean(`Time Between First/Last Detections (For Sorting)`)), 
            medianJourneyLength = easyViewingTime(median(`Time Between First/Last Detections (For Sorting)`)), 
            sdDevJourneyLength = easyViewingTime(sd(`Time Between First/Last Detections (For Sorting)`)), 
            minJourneyLength = easyViewingTime(max(`Time Between First/Last Detections (For Sorting)`)), 
            maxJourneyLength = easyViewingTime(min(`Time Between First/Last Detections (For Sorting)`))) %>%
  mutate(SequenceDIrection = "Upstream RB to HP") %>%
  pivot_longer(
    cols = -SequenceDIrection,
    names_to = c("Upstream RB to HP"),
    #names_pattern = "(mean|min|max|median|sd)(.*)",
    values_to = "value"
  )

datatable(summarizedUS, 
          caption = paste0("Upstream RB to HP Sequences Summarized (", nrow(RBHPSequences), " journeys): Non Avian-Predated Fish"),
  options = list(
    pageLength = 10,
    autoWidth = TRUE
  ),
  filter = list(
  position = 'top', clear = FALSE
),
  rownames = FALSE
  )

plot <- RBHPSequences %>%
  #mutate()
  ggplot(aes(x = abs(as.numeric(`Time Between First/Last Detections (For Sorting)`)),
             text = paste0("Range: ", easyViewingTime_vec(round(after_stat(xmin), 2)), " to ", 
                           easyViewingTime_vec(round(after_stat(xmax), 1)), #" seconds",
                    "<br>Count: ", after_stat(count))
             #text = `Time Between First/Last Detections (User Friendly)`
             )
         ) +
  geom_histogram(bins = 50, color = "steelblue", fill = "steelblue") +
  scale_x_log10(labels = scales::label_log()) +
  labs(
    title = "Log Duration Distribution of Upstream Journeys From RB to HP: Non-Avian Predated Tags",
    x = "Log Time Difference (seconds)",
    y = "Frequency", 
    caption = "Avian Predated Tags Excluded"
  ) +
  theme_classic()
ggplotly(plot, tooltip = "text")
```

### Predated Fish: Upstream from Red Barn To Hitching Post
```{r upstreamPredated, echo = FALSE, include=TRUE, warning=FALSE,message=FALSE,error=FALSE}
####UPSTREAM SEQUENCES
allEventsAvianOnly<- combinedData_df_list$All_Events %>%
    dplyr::filter(TAG %in% unique(indiv_datasets_list$avian_preddata$TagID)) 

HPRBSequencesPredated <- invisible(getSequences(allEventsAvianOnly, c("HP"), "", c("RB"), c("M1", "M2")))
RBHPSequencesPredated <- invisible(getSequences(allEventsAvianOnly, c("RB"), "", c("HP"), c("M1", "M2")))

#RBHPSequencesPredated
summarizedUS <- RBHPSequencesPredated %>%
  ungroup() %>%
  summarize(meanJourneyLength = easyViewingTime(mean(`Time Between First/Last Detections (For Sorting)`)), 
            medianJourneyLength = easyViewingTime(median(`Time Between First/Last Detections (For Sorting)`)), 
            sdDevJourneyLength = easyViewingTime(sd(`Time Between First/Last Detections (For Sorting)`)), 
            minJourneyLength = easyViewingTime(max(`Time Between First/Last Detections (For Sorting)`)), 
            maxJourneyLength = easyViewingTime(min(`Time Between First/Last Detections (For Sorting)`))) %>%
  mutate(SequenceDIrection = "Upstream RB to HP") %>%
  pivot_longer(
    cols = -SequenceDIrection,
    names_to = c("Upstream RB to HP"),
    #names_pattern = "(mean|min|max|median|sd)(.*)",
    values_to = "value"
  )

datatable(summarizedUS, 
          caption = paste0("Upstream RB to HP Sequences Summarized (", nrow(RBHPSequencesPredated), " journeys): Avian-Predated Tags"),
  options = list(
    pageLength = 10,
    autoWidth = TRUE
  ),
  filter = list(
  position = 'top', clear = FALSE
),
  rownames = FALSE
  )

plot <- RBHPSequencesPredated %>%
  #mutate()
  ggplot(aes(x = abs(as.numeric(`Time Between First/Last Detections (For Sorting)`)),
             text = paste0("Range: ", easyViewingTime_vec(round(after_stat(xmin), 2)), " to ", 
                           easyViewingTime_vec(round(after_stat(xmax), 1)), #" seconds",
                    "<br>Count: ", after_stat(count))
             #text = `Time Between First/Last Detections (User Friendly)`
             )
         ) +
  geom_histogram(bins = 50, color = "steelblue", fill = "steelblue") +
  scale_x_log10(labels = scales::label_log()) +
  labs(
    title = "Log Duration Distribution of Upstream Journeys From RB to HP: Predated Tags",
    x = "Log Time Difference (seconds)",
    y = "Frequency", 
    caption = "Avian Predated Tags Only"
  ) +
  theme_classic()
ggplotly(plot, tooltip = "text")
```

### Predated Fish: Downstream from Hitching Post To Red Barn

```{r downstreamPredated, echo = FALSE, include=TRUE, warning=FALSE,message=FALSE,error=FALSE}

summarizedDS <- HPRBSequencesPredated %>%
  ungroup() %>%
  summarize(meanJourneyLength = easyViewingTime(mean(`Time Between First/Last Detections (For Sorting)`)), 
            medianJourneyLength = easyViewingTime(median(`Time Between First/Last Detections (For Sorting)`)), 
            sdDevJourneyLength = easyViewingTime(sd(`Time Between First/Last Detections (For Sorting)`)), 
            minJourneyLength = easyViewingTime(max(`Time Between First/Last Detections (For Sorting)`)), 
            maxJourneyLength = easyViewingTime(min(`Time Between First/Last Detections (For Sorting)`))) %>%
  mutate(SequenceDIrection = "Downstream RB to HP") %>%
  pivot_longer(
    cols = -SequenceDIrection,
    names_to = c("Downstream RB to HP"),
    #names_pattern = "(mean|min|max|median|sd)(.*)",
    values_to = "value"
  )

datatable(summarizedDS, 
          caption = paste0("Downstream RB to HP Sequences Summarized (", nrow(HPRBSequencesPredated), " journeys): Avian-Predated Tags"),
  options = list(
    pageLength = 10,
    autoWidth = TRUE
  ),
  filter = list(
  position = 'top', clear = FALSE
),
  rownames = FALSE
  )

plot <- HPRBSequencesPredated %>%
  #mutate()
  ggplot(aes(x = abs(as.numeric(`Time Between First/Last Detections (For Sorting)`)),
             text = paste0("Range: ", easyViewingTime_vec(round(after_stat(xmin), 2)), " to ", 
                           easyViewingTime_vec(round(after_stat(xmax), 1)), #" seconds",
                    "<br>Count: ", after_stat(count))
             #text = `Time Between First/Last Detections (User Friendly)`
             )
         ) +
  geom_histogram(bins = 50, color = "steelblue", fill = "steelblue") +
  scale_x_log10(labels = scales::label_log()) +
  labs(
    title = "Log Duration Distribution of Downstream Journeys From HP to RB: Predated Tags",
    x = "Log Time Difference (seconds)",
    y = "Frequency", 
    caption = "Avian Predated Tags Only"
  ) +
  theme_classic()
ggplotly(plot, tooltip = "text")
```
## Evacuation Rate
```{r evacuation Rate, echo = FALSE, include=TRUE, warning=FALSE,message=FALSE,error=FALSE}
#gets all activity after predation date and ebfore ghost date (if applicable)
allEventsAvianOnlyWithpredatoinDate <- allEventsAvianOnly %>%
  left_join(indiv_datasets_list$avian_preddata[,c("TagID", "PredationDate")], by = c("TAG" = "TagID")) %>%
  left_join(indiv_datasets_list$ghostdata[,c("TagID", "GhostDate")], by = c("TAG" = "TagID")) %>%
  # if the tag has a ghost date and a pred date, take only data before the ghost date. if it has no ghsot date just do pred Date
  filter(Date >= PredationDate & (is.na(GhostDate) | Date < GhostDate)) 

allEventsAvianOnlyWithpredatoinDateSummazirsed <- allEventsAvianOnlyWithpredatoinDate %>%
  #distinct(TAG)
  group_by(TAG) %>%
  arrange(Datetime) %>%
  summarize(`Time Between Predation Date and Last Detection` = difftime(last(Date), first(Date), units = "days"))
  
evacuationRatesSummarized <- allEventsAvianOnlyWithpredatoinDateSummazirsed %>%
  ungroup() %>%
  summarize(
    `Mean Number of Days Between Predation Date and Last Detection (Evacuation)` = round(mean(`Time Between Predation Date and Last Detection`), 2), 
            `Median Number of Days Between Predation Date and Last Detection (Evacuation)` = round(median(`Time Between Predation Date and Last Detection`), 2), 
            `SD Number of Days Between Predation Date and Last Detection (Evacuation)` = as.difftime(round(sd(`Time Between Predation Date and Last Detection`), 2), units = 'days'), 
            `Maximum Number of Days Between Predation Date and Last Detection (Evacuation)` = round(max(`Time Between Predation Date and Last Detection`), 2), 
            `Minimum Number of Days Between Predation Date and Last Detection (Evacuation)` = round(min(`Time Between Predation Date and Last Detection`), 2))

evacuationRatesSummarizedLong <- evacuationRatesSummarized %>%
  mutate(evacStats = "Evacuation Rate Stats") %>%
  pivot_longer(
    cols = -evacStats,
    names_to = c("Evacuation Rate Stats"),
    #names_pattern = "(mean|min|max|median|sd)(.*)",
    values_to = "value"
  ) %>%
  select(-evacStats)

datatable(evacuationRatesSummarizedLong, 
          caption = paste0("Time Between Predation Date and Last Detection: Summarized. All tags from predation file included (n = ", nrow(allEventsAvianOnlyWithpredatoinDateSummazirsed), ")"),
  options = list(
    pageLength = 10,
    autoWidth = TRUE
  ),
  filter = list(
  position = 'top', clear = FALSE
),
  rownames = FALSE
  )

    #`Average  = mean(`Time Between Predation Date and Last Detection`))

#tagsToCheck <- anti_join(indiv_datasets_list$avian_preddata, allEventsAvianOnlyWithpredatoinDateSummazirsed, by = c("TagID" = "TAG"))

```
### Seasonality

```{r seasonality, echo = FALSE, include=TRUE, warning=FALSE,message=FALSE,error=FALSE, fig.cap=paste0("All tags in predated file post-predation date (n = ", nrow(indiv_datasets_list$avian_preddata), "). Mobile Runs and Release data excluded")}
#create seasonlity graph with known mergansers and avian predation file
#both for movements and raw detections

###Movements

predationMovementsDataPostPredationDate <- movements_list$Movements_df %>%
  dplyr::filter(TAG %in% unique(indiv_datasets_list$avian_preddata$TagID), 
                !det_type %in% c("Mobile Run")
  ) %>%
  left_join(indiv_datasets_list$avian_preddata[,c("TagID", "PredationDate")], by = c("TAG" = "TagID")) %>%
  left_join(indiv_datasets_list$ghostdata[,c("TagID", "GhostDate")], by = c("TAG" = "TagID")) %>%
  # if the tag has a ghost date and a pred date, take only data before the ghost date. if it has no ghsot date just do pred Date
  filter(Date >= PredationDate & (is.na(GhostDate) | Date < GhostDate)) 

  # filter(!Species %in% c("TGM"), 
  #        
  #        )
#Annual Figure of Upstream vs downstream movements
seasonal_movts <- predationMovementsDataPostPredationDate %>%
  filter(!movement_only %in% c("Initial Release")) %>%
  group_by(Month = lubridate::month(Date), Day = day(Date), movement_only) %>%
  summarise(total_events = n())

plot <- seasonal_movts %>%
            mutate(`Month-Day` = (parse_date_time(paste(Month, Day), "md"))) %>%
            ggplot(aes(x = `Month-Day`, y = total_events, fill = movement_only)) +
            geom_bar(stat = "identity", position = "dodge") +
            theme_classic() +
            labs(title = "Predated Tags Seasonal Daily Movements", x = "Day", y = "Counts") +
            scale_x_datetime(date_labels = "%b") +
            scale_fill_manual(values = movementColors)
          
ggplotly(plot) 

```


```{r seasonalityRawMovements, echo = FALSE, include=TRUE, warning=FALSE,message=FALSE,error=FALSE, fig.cap=paste0("All tags in predated file post-predation date (n = ", nrow(indiv_datasets_list$avian_preddata), "). Mobile Runs and Release data excluded")}
seasonal_movts <- allEventsAvianOnlyWithpredatoinDate %>%
  filter(!Event %in% c("Release", "M1", "M2")) %>%
  group_by(Month = lubridate::month(Date), Day = day(Date), Event) %>%
  summarise(total_events = n())

plot <- seasonal_movts %>%
            mutate(`Month-Day` = (parse_date_time(paste(Month, Day), "md"))) %>%
            ggplot(aes(x = `Month-Day`, y = total_events, fill = Event)) +
            geom_bar(stat = "identity", position = "dodge") +
            theme_classic() +
            labs(title = "Predated Tags Seasonal Raw Detections", x = "Day", y = "Counts") +
            scale_x_datetime(date_labels = "%b") 
          
ggplotly(plot) 
```

